services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Diversworld\CalendarEditorBundle\Controller\Module\ModuleEventEditor:
    arguments:
      $requestStack: '@request_stack'
      $scopeMatcher: '@contao.routing.scope_matcher'
      $logger: '@logger'

  Diversworld\CalendarEditorBundle\Controller\Module\ModuleCalendarEdit:
    calls:
      - [ setCheckAuthService, [ '@Diversworld\CalendarEditorBundle\Services\CheckAuthService' ] ]

  Diversworld\CalendarEditorBundle\Services\CheckAuthService:
    autowire: true
    autoconfigure: true
    public: true

  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - [ setFramework, [ '@contao.framework' ] ]

    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - [ setContainer, [ '@service_container' ] ]
