services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Diversworld\CalendarEditorBundle\Controler\Modules\ModuleCalendarEdit:
    calls:
      - [ setCheckAuthService, [ '@Diversworld\CalendarEditorBundle\Services\CheckAuthService' ] ]

  Diversworld\CalendarEditorBundle\Controler\Modules\ModuleEventEditor:
    arguments:
      - '@?logger'
    tags:
      - { name: monolog.logger, channel: contao.general }

  Diversworld\CalendarEditorBundle\Services\CheckAuthService:
    autowire: true
    autoconfigure: true
    public: true

  monolog.logger.contao.general:
    class: Monolog\Logger
    arguments: ['contao.general']
    tags:
      - { name: monolog.logger, channel: contao.general }

  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - [ setFramework, [ '@contao.framework' ] ]

    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - [ setContainer, [ '@service_container' ] ]
